name: TEST

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configurando Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Instalando dependencias
        run: go mod download

      - name: Ejecución de pruebas
        run: go test
